class_name ClientHeaders extends RefCounted


enum Headers {
	PING,
	ACCESS_ACCOUNT,
	CREATE_ACCOUNT,
	DELETE_ACCOUNT,
	RECOVER_ACCOUNT,
	CHANGE_PASSWORD,
	REQUEST_CHARACTERS,
	CREATE_CHARACTER,
	DELETE_CHARACTER,
	SELECT_CHARACTER,
	MOVE_CHARACTER,
	CHAT_MESSAGE
}
