class_name ServerHeaders extends RefCounted

enum Headers {
	PING,
	ALERT,
	ACCESS_ACCOUNT,
	CREATE_ACCOUNT,
	DELETE_ACCOUNT,
	RECOVER_ACCOUNT,
	CHANGE_PASSWORD,
	CHARACTER_LIST,
	CREATE_CHARACTER,
	DELETE_CHARACTER,
	SELECT_CHARACTER,
	MAP_CHARACTERS_TO,
	NEW_CHARACTER_TO,
	MOVE_CHARACTER,
	DISCONNECT_CHARACTER,
	TELEPORT_CHARACTER,
}
