class_name ServerHeaders extends RefCounted

enum Headers {
	PONG,
	ALERT,
	ACCESS_SUCCESSFUL,
	ACCOUNT_CREATED,
	ACCOUNT_DELETED,
	ACCOUNT_RECOVERED,
	PASSWORD_CHANGED,
	CHARACTER_LIST,
	CHARACTER_CREATED,
	CHARACTER_DELETED,
	CHARACTER_SELECTED,
	MAP_CHARACTERS_TO,
	NEW_CHARACTER_TO,
	CHARACTER_MOVED,
	CHARACTER_DISCONNECTED,
	CHARACTER_TELEPORTED,
}
